shinhan-hackathon-the-guardians/backend

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/entity/Approval.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/entity/ChatbotPrompt.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/entity/Family.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/guardian/entity/GuardianTest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/notification/entity/Notification.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/notification/entity/NotificationResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/entity/PaymentLimit.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/entity/QuestionBank.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/entity/Transaction.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/entity/TransactionRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/User.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/withdrawal/entity/WithdrawalBlock.java
src/main/resources/application.yaml

- #4 
- Entity 생성
- DB에 맞는 Entity 생성
-

[Setting/#4] Entity 설정

---

build.gradle
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/controller/QuestionBankController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/repository/QuestionBankRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/response/QuestionListResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/response/QuestionResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/service/QuestionBankService.java

resolve #9 
feat/#9
- 문제 20개 불러오기 기능 개발

[#9] 가디언 테스트 문제 20개 불러오기 기능 개발

---

build.gradle
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/repository/UserRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/dto/LoginRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/dto/UserPrinciple.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/service/UserDetailsServiceImpl.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/service/handler/AuthenticationSuccessHandlerImpl.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/service/handler/LogoutHandlerDecorator.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/config/PasswordEncoderConfig.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/config/WebSecurityConfig.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/filter/LoginAuthenticationFilter.java

- resolve: #6 
- 세션기반 로그인, 로그아웃 추가
- 개발 편의를 위한 root path permitAll
- 명세서 작성 이후 로그인 반환 데이터 추가

[Setting/#6] session기반 로그인/로그아웃 추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/entity/QuestionBank.java

resolve #13 
- QuestionBank erd에 explanation속성 추가

[#13]  QuestionBank erd에 explanation속성 추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/controller/TransactionController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/DepositRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/TransferRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/WithdrawalRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/service/TransactionService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/service/UserService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/dto/UserPrincipal.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/service/UserDetailsServiceImpl.java

- #23 
- 입금, 출금, 이체 기본기능 구현
- TransactionController
- TansactionService
- 현재 Transaction 서비스는 기본 거래 기능만 구현한 상태
- 추가로 필요한 기능 : Rule Check, 알림, 승인/차단

[Feature/#23] transaction: 입금, 출금, 이체 기본기능 구현

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/notification/entity/NotificationResponseStatus.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/notification/entity/ResponseStatus.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/entity/TransactionRequest.java

- resolve: #18 
- Entity객체명 수정
- Entity객체 필드 타입 변경
- approveCount 초기화 추가

[Fix/#18] 설계 변경에 따른 Entity 수정

---

src/main/java/com/shinhan_hackathon/the_family_guardian/bank/dto/request/CheckAuthCodeRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/dto/request/OpenAccountAuthRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/dto/response/CheckAuthCodeResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/dto/response/OpenAccountAuthResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/service/AccountAuthService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/service/AccountService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/util/BankUtil.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/controller/UserController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/dto/AccountAuthCheckRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/dto/AccountAuthResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/dto/AccountAuthSendRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/dto/SignupRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/Gender.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/User.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/service/UserService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/dto/UserPrincipal.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/config/RedisConfig.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/service/RedisService.java
src/main/resources/application.yaml
src/test/java/com/shinhan_hackathon/the_family_guardian/bank/account/BankAccountAuthTest.java
src/test/java/com/shinhan_hackathon/the_family_guardian/bank/account/BankAccountTest.java

- resolve: #19 
- 1원송금 & 인증
- 회원가입
- 유효한 계좌정보가 있어야 동작
- 사용자에 대한 계좌를 미리 생성하고 공유해두어야 할듯.
- 사용자에 대한 계좌 입금 알림은 log로 대체해두었음. log에 기록되는 인증코드를 임시로 사용(추후 알림으로 대체예정)

[Feat/#19] 1원송금을 사용한 회원가입

---

build.gradle
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/service/AccountAuthService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/service/AccountService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/bank/util/BankUtil.java
src/main/resources/application.yaml
src/test/java/com/shinhan_hackathon/the_family_guardian/bank/account/BankAccountTest.java

- resolve: #28 
- dotenv 의존성을 제거했습니다.

[Fix/#28] Dotenv 의존성 제거

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/controller/FamilyController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/AddFamilyMemberRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/CreateFamilyRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/CreateFamilyResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/FamilyInfoResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/UpdateFamilyRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/repository/FamilyRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/service/FamilyService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/GuardianAuthority.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/Role.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/User.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/dto/UserPrincipal.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/util/AuthUtil.java

- resolve: #20 
- 그룹 생성
- 그룹 정보조회
- AuthUtil 생성

[Feat/#20] 그룹 생성, 정보조회 구현

---

build.gradle
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/config/MongoConfig.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/controller/ChatController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/entity/ChatMessage.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/repository/ChatMessageRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/response/ChatHistoryResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/response/ChatHistoryResponseWrapper.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/service/ChatService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/dto/SignupRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/service/UserService.java
src/main/resources/application.yaml

resolve #31 
- mongoDB에저장
- ChatHistory 조회 기능 개발

[#31]  mongoDB에저장, ChatHistory 조회 기능 개발

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/controller/ApprovalController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/dto/ApprovalInfoResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/dto/ApprovalReplyRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/dto/ApprovalReplyResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/entity/AcceptStatus.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/entity/Approval.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/repository/ApprovalRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/service/ApprovalService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/controller/FamilyController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/AddFamilyMemberRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/AddFamilyMemberResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/UpdateFamilyResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/entity/Family.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/service/FamilyService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/controller/UserController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/repository/UserRepository.java

- resolve: #35 
- 그룹 설정 구현
- 그룹 초대 구현
- 그룹 초대 응답 구현

[Feat/#35] 그룹 설정, 그룹 초대, 초대 응답 개발

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/entity/Transaction.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/service/TransactionService.java

- #40 
- Transction 실행 메서드 추가
- Approve Count 증가 메서드 추가
- `executeWithdrawalTransction()`
- `executeTransferTransction()`
- `executePaymentTransaction()`
- `updateTransactionApproveCount()`
- TODO: 주석으로 필요한 실행흐름을 상세히 적어 놓았으니 참고하길 바람

[Feature/#40] execute transaction 메서드 추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/controller/ChatController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/dto/response/ChatHistoryResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/dto/response/ChatHistoryResponseWrapper.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/service/ChatService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/controller/QuestionBankController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/dto/request/QuestionCompleteRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/dto/response/QuestionListResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/dto/response/QuestionResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/service/QuestionBankService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/User.java

resolve #41 
- 가디언 테스트 완료 버튼 기능 개발
- pass가 true면 GUARDIAN으로 LEVEL바꾸기
- pass가 false면 그대로 유지

[#41] - 가디언 테스트 완료 버튼

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/dto/response/QuestionResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/service/QuestionBankService.java

resolve #50 
-  문제 response에 pk, explanation 추가
- QuestionResponse, QuestionBankService 수정

[#50] - 문제 response에 pk, explanation 추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/controller/QuestionBankController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/repository/QuestionBankRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/questionbank/service/QuestionBankService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/User.java

resolve #54 
- 문제은행 100문 조회 (랜덤 순서)
- User의 Gender필드 EnumType.STRING추가

[#54] - 문제은행 100문 조회, User의 Gender EnumType.STRING추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/notification/service/NotificationService.java

- #60 
- NotificationService와 TransactionService의 순환참조 제거
- NotifcationService에서 TransactionService 의존성 제거
-

[Hotfix] #60 순환참조 제거

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/entity/Transaction.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/repository/TransactionRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/service/TransactionService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/config/SchedulingConfig.java

- #45 
- 출금, 이체, 결제에 대해 10분 경과 시 요청 실패 로직 추가
- `SchedulerConfig`
- `TransactionRepostiroy.findByTransactionStatus()`
- `TransactionService.updateTimeoutTransaction()`
-

[Feature/#45] 요청 시간제한 로직 추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/service/TransactionService.java

- #65 
- `@Scheduled`의 접근 제어자 문제
- `TransactionService.updateTimeoueTransaction()` : `private` -> `public`
-

[Hotfix] #65 접근 제어자 문제

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/controller/PaymentLimitController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/dto/UpdateLimitRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/dto/UpdateLimitResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/entity/LimitPeriod.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/entity/PaymentLimit.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/service/PaymentLimitService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/controller/UserController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/service/UserService.java

- resolve: #62 
- 결제 제한 생성 및 업데이트 구현

[Feat/#62] 결제 제한 api 구현

---

src/main/resources/data.sql

resolve #63 
- data.sql 더미데이터 추가
- data.sql

[#63] data.sql 더미데이터 추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/global/handler/GlobalExceptionHandler.java

- #76 
- 전역 Exception Handler 구현
- CustomExceptionHandler
-

[Feat] #76 Add exception handler

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/chatbot/controller/ChatController.java

resolve #78 
- 챗봇에 프롬프트 추가 
- ChatController에 prompt (String) 추가

[#78] chatbot prompt추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/entity/Approval.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/approval/service/ApprovalService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/AddFamilyMemberRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/service/FamilyService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/controller/UserController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/dto/LoginResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/dto/SignupResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/entity/User.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/service/UserService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/service/handler/AuthenticationSuccessHandlerImpl.java

- resolve: #83 
- 요구사항이 변경에 따른 수정
- 가족 구성원 추가시 관계 정보 추가
- Approval Entity에 관계정보 추가
- 로그인, 회원가입시 유저정보 반환
- 
-

[Fix/#83]  요구사항 변경에 따른 api 입력, 반환 타입 변경

---

src/main/java/com/shinhan_hackathon/the_family_guardian/global/auth/service/handler/AuthenticationSuccessHandlerImpl.java

- resolve: #88 
- authentication success handler response의 character encoding 설정 추가

[Add] #88 - response의 CharacterEncoding 설정 추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/DepositRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/PaymentRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/TransferRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/WithdrawalRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/service/TransactionService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/repository/UserRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/service/UserService.java

- #90 
- 입금, 출금, 이체, 결제 시 사용자 정보를 계좌정보로 불러오기로 변경
- `findByAccountNumber()`
-

[Fix/#90] 입금, 출금, 이체, 결제 시 사용자 정보를 계좌정보로 불러오기로 변경

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/controller/FamilyController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/dto/FamilyUserRoleResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/service/FamilyService.java

- resolve: #101 
- 유저 역할조회 api 구현
- 응답용 dto 추가
- 엔드포인트 추가
- 역할조회 메서드 구현

[Feat/#101] 유저 역할조회 구현

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/controller/FamilyController.java

- resolve: #101
- 반환값을 추가했습니다.

[Fix/#101] getUserRole() 반환값 추가

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/controller/UserController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/dto/UsernameCheckRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/repository/UserRepository.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/user/service/UserService.java

- resolve: #97 
- 유저 계정(로그인 ID) 중복체크 추가

[Feat/#97] 유저 계정 중복체크 추가

---

src/main/resources/data.sql

resolve #103 
- payment_limit의 start_date 더미데이터 수정
- data.sql 수정

[#103] data.sql수정

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/family/service/FamilyService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/notification/service/NotificationService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/controller/PaymentLimitController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/payment/service/PaymentLimitService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/service/TransactionService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/global/fcm/FcmSender.java
src/main/resources/data.sql

- resolve: #106 
- fcm 타이틀 수정, body를 json으로 수정
- 단건 한도 확인 로직 수정

[Fix/#106] 알림 메시지 타이틀 & body 수정

---

src/main/java/com/shinhan_hackathon/the_family_guardian/bank/service/AccountService.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/controller/TransactionController.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/AccountBalanceRequest.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/AccountBalanceResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/service/TransactionService.java
src/test/java/com/shinhan_hackathon/the_family_guardian/bank/account/BankAccountTest.java

- #109 
- 계좌 정보를 받아 잔액을 반환
-
-

[Feat/#109] 계좌 잔액 조회

---

src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/dto/AccountBalanceResponse.java
src/main/java/com/shinhan_hackathon/the_family_guardian/domain/transaction/service/TransactionService.java

[Hotfix] #200 User
